openapi: 3.0.0
info:
  description: For sending sms using villa
  version: '1.1'
  title: send-sms-api
  contact:
    email: nwanavit@tenxor.sh
    
  
paths:
  /Prod/sendSms:
    post:
      summary: send sms
      operationId: sendSms
      description: send sms to a phone
      responses:
        '200':
          description: 'sending success'
        '400':
          description: 'something is wrong, please check error message'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendSms'
        description: send sms to users, required
security:
  - awsSigV4: []
components:
  securitySchemes:
    awsSigV4:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    SendSms:
      type: object
      properties:
        subject:
          type: string
          example: "test subject"
          description: REQUIRED Subjects must be ASCII text that begins with a letter, number, or punctuation mark; must not include line breaks or control characters; and must be less than 100 characters long.
        message:
          type: string
          example: "test message"
          description: REQUIRED The message you want to send. each message can contain up to 140 characters. This character limit depends on the encoding schema. For example, an SMS message can contain 160 GSM characters, 140 ASCII characters, or 70 UCS-2 characters. If you publish a message that exceeds this size limit, Amazon SNS sends the message as multiple messages, each fitting within the size limit. Messages aren't truncated mid-word but are cut off at whole-word boundaries. The total size limit for a single SMS Publish action is 1,600 characters.
        phoneNumber:
          type: string
          example: "+16282079687"
          description: REQUIRED The phone number to which you want to deliver an SMS message. Use E.164 format.
        referenceId:
          type: string
          example: "gb12345"
          description: "REQUIRED this is for reference and will be used as hash key for the cache"
      description: send sms 
      required: 
        - subject
        - message
        - phoneNumber
        - referenceId
servers:

  - url: https://rxqezebd98.execute-api.ap-southeast-1.amazonaws.com
    description: villa-sms-server